// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PitaSmart.Infrastructure.Persistence;

#nullable disable

namespace PitaSmart.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PitaSmartDbContext))]
    partial class PitaSmartDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PitaSmart.Domain.Agroquimicos.Entities.FichaTecnica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContenidoHtml")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("FechaActualizacion")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("InsumoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlDocumento")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("InsumoId");

                    b.ToTable("FichasTecnicas", (string)null);
                });

            modelBuilder.Entity("PitaSmart.Domain.Agroquimicos.Entities.Insumo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("CategoriaToxico")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DosisMaxima")
                        .HasColumnType("decimal(10,4)");

                    b.Property<decimal>("DosisMinima")
                        .HasColumnType("decimal(10,4)");

                    b.Property<string>("Fabricante")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("IngredienteActivo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NombreComercial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RegistroAgrocalidad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("TipoProducto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UnidadDosis")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RegistroAgrocalidad")
                        .IsUnique();

                    b.ToTable("Insumos", (string)null);
                });

            modelBuilder.Entity("PitaSmart.Domain.Agroquimicos.Entities.PeriodoCarencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cultivo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("DiasCarencia")
                        .HasColumnType("int");

                    b.Property<string>("FuenteRegulacion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("InsumoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InsumoId", "Cultivo")
                        .IsUnique();

                    b.ToTable("PeriodosCarencia", (string)null);
                });

            modelBuilder.Entity("PitaSmart.Domain.Aplicaciones.Entities.AplicacionQuimico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AreaAplicadaHa")
                        .HasColumnType("decimal(10,4)");

                    b.Property<DateTimeOffset>("ClientTimestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("CostoTotal")
                        .HasColumnType("decimal(12,2)");

                    b.Property<bool>("CreadoOffline")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("DiasCarenciaAplicables")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("FechaAplicacion")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("FechaFinCarencia")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("InsumoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LoteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MetodoAplicacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("OperadorNombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LoteId");

                    b.HasIndex("LoteId", "FechaFinCarencia");

                    b.ToTable("Aplicaciones", (string)null);
                });

            modelBuilder.Entity("PitaSmart.Domain.Cosecha.Entities.Cosecha", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("BloqueadaPorCarencia")
                        .HasColumnType("bit");

                    b.Property<string>("CalidadGrado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset>("ClientTimestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Comprador")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("CreadoOffline")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("FechaCosecha")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal?>("IngresoTotal")
                        .HasColumnType("decimal(12,2)");

                    b.Property<Guid>("LoteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("PesoTotalKg")
                        .HasColumnType("decimal(12,4)");

                    b.Property<decimal?>("PrecioVentaKg")
                        .HasColumnType("decimal(10,4)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LoteId");

                    b.ToTable("Cosechas", (string)null);
                });

            modelBuilder.Entity("PitaSmart.Domain.Costos.Entities.CostoLote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AplicacionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("ClientTimestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CosechaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("CreadoOffline")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("EliminadoAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<Guid>("LoteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(12,2)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LoteId", "Fecha");

                    b.ToTable("CostosLote", (string)null);
                });

            modelBuilder.Entity("PitaSmart.Domain.Costos.Entities.Finca", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AreaTotalHa")
                        .HasColumnType("decimal(10,4)");

                    b.Property<string>("Canton")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Parroquia")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Provincia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Fincas", (string)null);
                });

            modelBuilder.Entity("PitaSmart.Domain.Costos.Entities.IngresoLote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comprador")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("CosechaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<decimal>("KgVendidos")
                        .HasColumnType("decimal(12,4)");

                    b.Property<Guid>("LoteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("PrecioKg")
                        .HasColumnType("decimal(10,4)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<decimal>("TotalVenta")
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LoteId", "Fecha");

                    b.ToTable("IngresosLote", (string)null);
                });

            modelBuilder.Entity("PitaSmart.Domain.Costos.Entities.Lote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<decimal>("AreaHa")
                        .HasColumnType("decimal(10,4)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cultivo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly?>("FechaInicioSiembra")
                        .HasColumnType("date");

                    b.Property<Guid>("FincaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("Latitud")
                        .HasColumnType("float");

                    b.Property<double?>("Longitud")
                        .HasColumnType("float");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FincaId");

                    b.ToTable("Lotes", (string)null);
                });

            modelBuilder.Entity("PitaSmart.Domain.Costos.Entities.PrecioMercado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cultivo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly>("FechaPublicacion")
                        .HasColumnType("date");

                    b.Property<string>("Fuente")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("PrecioKg")
                        .HasColumnType("decimal(10,4)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Vigente")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Cultivo", "Vigente");

                    b.ToTable("PreciosMercado", (string)null);
                });

            modelBuilder.Entity("PitaSmart.Domain.Identidad.Entities.CredencialPasskey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AaGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("CredentialId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varbinary(512)");

                    b.Property<string>("CredentialType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DispositivoNombre")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("FechaRegistro")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("PublicKey")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("varbinary(1024)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<long>("SignCount")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CredentialId")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("CredencialesPasskey", (string)null);
                });

            modelBuilder.Entity("PitaSmart.Domain.Identidad.Entities.SesionDispositivo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<string>("AppVersion")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("FechaExpiracion")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Plataforma")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RefreshTokenHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "DeviceId");

                    b.ToTable("SesionesDispositivo", (string)null);
                });

            modelBuilder.Entity("PitaSmart.Domain.Identidad.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Cedula")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<DateTimeOffset>("FechaRegistro")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Telefono")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTimeOffset?>("UltimoAcceso")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Cedula")
                        .IsUnique()
                        .HasFilter("[Cedula] IS NOT NULL");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("PitaSmart.Domain.Sincronizacion.Entities.OperacionPendiente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ClientTimestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("EntidadId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntidadTipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ErrorDetalle")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("IntentoNumero")
                        .HasColumnType("int");

                    b.Property<Guid>("OperacionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ProcesadoAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<byte[]>("RowVersionAnterior")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OperacionId")
                        .IsUnique();

                    b.HasIndex("DeviceId", "ProcesadoAt");

                    b.ToTable("SyncOperacionesLog", (string)null);
                });

            modelBuilder.Entity("PitaSmart.Domain.Agroquimicos.Entities.FichaTecnica", b =>
                {
                    b.HasOne("PitaSmart.Domain.Agroquimicos.Entities.Insumo", "Insumo")
                        .WithMany("FichasTecnicas")
                        .HasForeignKey("InsumoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Insumo");
                });

            modelBuilder.Entity("PitaSmart.Domain.Agroquimicos.Entities.Insumo", b =>
                {
                    b.OwnsOne("PitaSmart.Domain.Agroquimicos.ValueObjects.Concentracion", "Concentracion", b1 =>
                        {
                            b1.Property<Guid>("InsumoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Unidad")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("ConcentracionUnidad");

                            b1.Property<decimal>("Valor")
                                .HasColumnType("decimal(10,4)")
                                .HasColumnName("ConcentracionValor");

                            b1.HasKey("InsumoId");

                            b1.ToTable("Insumos");

                            b1.WithOwner()
                                .HasForeignKey("InsumoId");
                        });

                    b.Navigation("Concentracion")
                        .IsRequired();
                });

            modelBuilder.Entity("PitaSmart.Domain.Agroquimicos.Entities.PeriodoCarencia", b =>
                {
                    b.HasOne("PitaSmart.Domain.Agroquimicos.Entities.Insumo", "Insumo")
                        .WithMany("PeriodosCarencia")
                        .HasForeignKey("InsumoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Insumo");
                });

            modelBuilder.Entity("PitaSmart.Domain.Aplicaciones.Entities.AplicacionQuimico", b =>
                {
                    b.OwnsOne("PitaSmart.Domain.Aplicaciones.ValueObjects.CoordenadasGps", "CoordenadasGps", b1 =>
                        {
                            b1.Property<Guid>("AplicacionQuimicoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<double>("Latitud")
                                .HasColumnType("float")
                                .HasColumnName("GpsLatitud");

                            b1.Property<double>("Longitud")
                                .HasColumnType("float")
                                .HasColumnName("GpsLongitud");

                            b1.HasKey("AplicacionQuimicoId");

                            b1.ToTable("Aplicaciones");

                            b1.WithOwner()
                                .HasForeignKey("AplicacionQuimicoId");
                        });

                    b.OwnsOne("PitaSmart.Domain.Aplicaciones.ValueObjects.Dosis", "Dosis", b1 =>
                        {
                            b1.Property<Guid>("AplicacionQuimicoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Cantidad")
                                .HasColumnType("decimal(10,4)")
                                .HasColumnName("DosisCantidad");

                            b1.Property<string>("Unidad")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("DosisUnidad");

                            b1.HasKey("AplicacionQuimicoId");

                            b1.ToTable("Aplicaciones");

                            b1.WithOwner()
                                .HasForeignKey("AplicacionQuimicoId");
                        });

                    b.Navigation("CoordenadasGps");

                    b.Navigation("Dosis")
                        .IsRequired();
                });

            modelBuilder.Entity("PitaSmart.Domain.Costos.Entities.CostoLote", b =>
                {
                    b.HasOne("PitaSmart.Domain.Costos.Entities.Lote", "Lote")
                        .WithMany("Costos")
                        .HasForeignKey("LoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lote");
                });

            modelBuilder.Entity("PitaSmart.Domain.Costos.Entities.IngresoLote", b =>
                {
                    b.HasOne("PitaSmart.Domain.Costos.Entities.Lote", "Lote")
                        .WithMany("Ingresos")
                        .HasForeignKey("LoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lote");
                });

            modelBuilder.Entity("PitaSmart.Domain.Costos.Entities.Lote", b =>
                {
                    b.HasOne("PitaSmart.Domain.Costos.Entities.Finca", "Finca")
                        .WithMany("Lotes")
                        .HasForeignKey("FincaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Finca");
                });

            modelBuilder.Entity("PitaSmart.Domain.Identidad.Entities.CredencialPasskey", b =>
                {
                    b.HasOne("PitaSmart.Domain.Identidad.Entities.Usuario", "Usuario")
                        .WithMany("Credenciales")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PitaSmart.Domain.Identidad.Entities.SesionDispositivo", b =>
                {
                    b.HasOne("PitaSmart.Domain.Identidad.Entities.Usuario", "Usuario")
                        .WithMany("Sesiones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PitaSmart.Domain.Agroquimicos.Entities.Insumo", b =>
                {
                    b.Navigation("FichasTecnicas");

                    b.Navigation("PeriodosCarencia");
                });

            modelBuilder.Entity("PitaSmart.Domain.Costos.Entities.Finca", b =>
                {
                    b.Navigation("Lotes");
                });

            modelBuilder.Entity("PitaSmart.Domain.Costos.Entities.Lote", b =>
                {
                    b.Navigation("Costos");

                    b.Navigation("Ingresos");
                });

            modelBuilder.Entity("PitaSmart.Domain.Identidad.Entities.Usuario", b =>
                {
                    b.Navigation("Credenciales");

                    b.Navigation("Sesiones");
                });
#pragma warning restore 612, 618
        }
    }
}
